### ISSUE TITLE
Encontrar la forma de procesar correctamente el archivo "actas.htm"

### ISSUE THREAD

**Issue by germaaan** [elecciones-ugr/actas#1]
No consigo encontrar la forma de procesar bien las tablas, porque por nombre de campo no sale bien, accediendo al árbol del documento no consigo organizarlo y por profundidad directamente no me sale nada.  A ver si puedes arrojarme un poco de claridad.

**Comment by JJ** [comment]
Lo he ejecutado y lo imprime todo. Aparte del problema del conjunto de caracteres, que se podrá solucionar, ¿qué problema hay? ¿Las filas y columnas son diferentes?

**Comment by germaaan** [comment]
Pues lo que te acabo de comentar, como no se puede hacer con el HTML::TableExtract hacerlo con el Mojo::DOM.
